//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Game = new HashSet<Game>();
            this.Game1 = new HashSet<Game>();
            this.Game2 = new HashSet<Game>();
            this.Game3 = new HashSet<Game>();
            this.Game4 = new HashSet<Game>();
            this.Game5 = new HashSet<Game>();
            this.Game6 = new HashSet<Game>();
        }
    
        public int IDimage { get; set; }
        public byte[] image { get; set; }
        public string name { get; set; }
        public string hint1 { get; set; }
        public string hint2 { get; set; }
        public string info { get; set; }
        public decimal latitude { get; set; }
        public decimal longitude { get; set; }
    
        public virtual ICollection<Game> Game { get; set; }
        public virtual ICollection<Game> Game1 { get; set; }
        public virtual ICollection<Game> Game2 { get; set; }
        public virtual ICollection<Game> Game3 { get; set; }
        public virtual ICollection<Game> Game4 { get; set; }
        public virtual ICollection<Game> Game5 { get; set; }
        public virtual ICollection<Game> Game6 { get; set; }
    }
}
