//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessWhere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public RegisteredUser()
        {
            this.SavedGames = new HashSet<SavedGames>();
        }
    
        public int IDRegUser { get; set; }
        public int IDUser { get; set; }
        public byte[] avatar { get; set; }
        public string password { get; set; }
        public Nullable<int> coins { get; set; }
        public Nullable<long> highscore { get; set; }
        public string IDBestGame { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<SavedGames> SavedGames { get; set; }
    }
}
